-- REVOKE ALL ON DATABASE Beacons FROM PUBLIC;

-- CREATE ROLE beacon_admin;
-- CREATE ROLE data_entry;
-- CREATE ROLE viewer;

--GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO beacon_admin;
--GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO beacon_admin;

--GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA PUBLIC TO data_entry;
--GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO data_entry;

--GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO viewer;

